..  |ACC|           replace:: Austin Community College
..  _ACC:           http://www.austincc.edu/
..  |VL|            replace:: VisualLogic
..  _VL:            http://www.visuallogic.org
..  |VB|            replace:: VirtualBox
..  _VB:            https://www.virtualbox.org/
..  |WWW|           replace:: World-Wide-Web
..  |RST|           replace:: reStructuredText
..  _RST:           http://docutils.sourceforge.net/rst.html
..  |WE|            replace:: WIndows Explorer

..  |pylit| replace::   PyLiT
..  _catch.hpp:     https://github.com/catchorg/Catch2
..  _CLion:         https://www.jetbrains.com/clion/
..  _Donald Knuth:  https://en.wikipedia.org/wiki/Donald_Knuth
..  _Git:           https://git-scm.com/
..  _GitHub:        https://github.com/
..  _GitLab:        https://about.gitlab.com/
..  _GLUT:          https://www.opengl.org/resources/libraries/glut/
..  _Google:        https://www.google.com/
..  _Gravatar:      https://en.gravatar.com/
..  _gVim:          https://www.vim.org/
..  _HomeBrew:      https://brew.sh/
..  _JetBrains:     https://www.jetbrains.com/
..  _LaTeX:         https://www.latex-project.org/
..  _MacVim:        https://github.com/macvim-dev
..  _MinGW-w64:     https://sourceforge.net/projects/mingw-w64/
..  _Nasm:          http://nasm.us/
..  _OpenGL:        https://www.opengl.org/
..  _Parallels:     https://www.parallels.com/
..  _Ruby:          https://www.ruby-lang.org/en/
..  _Scratch:       https://scratch.mit.edu/
..  _Sphinx:        http://sphinx-doc.org/
..  _TravisCI:      https://travis-ci.org/ 
..  _Ubuntu:        http://www.ubuntu.com/
..  _Vagrant:       https://www.vagrantup.com/
..  _Verilog:       http://www.verilog.com/
..  _Vim:           http://www.vim.org/
..  _VMware:        https://www.vmware.com/
..  _VirtualBox:    https://www.virtualbox.org/
